### ISSUE TITLE
Collisions bugged

### ISSUE THREAD

**Issue by realTronsi** [elbywan/quadtree-lib#13] opened 2020-08-08 17:40 UTC
```javascript

             //qt.colliding
             function (element1, element2) {
                  return (
                    dist(element1.x, element1.y, element2.x, element2.y) <
                    element1.width + element2.width
                  );
                }

//dist function
function dist(x1, y1, x2, y2) {
  return Math.sqrt(Math.pow(x1 - x2, 2) + Math.pow(y1 - y2, 2));
}
```

I inserted my own circle collision script, but it doesn't detect any collisions outside of its quadtree sector.

It seems to also happen with the default bounding box collision algorithm.

**Comment by elbywan** [comment] 2020-08-08 22:24
Hi @realTronsi,

Could you please be a bit more specific about the issue?

I tried to reproduce quickly but it seems to be working on my side.

```js
/* Default algorithm */

const Quadtree = require("quadtree-lib")

const quadtree = new Quadtree({
  width: 100,
  height: 100
})

const elements = [
  {x: 0, y: 0, width: 1, height: 5},
  {x: 0, y: 4, width: 1, height: 1}
]

quadtree.pushAll(elements)

console.log(quadtree.colliding(elements[0]))
// [ { x: 0, y: 4, width: 1, height: 1 } ]
```

```js
/* Circle collision algorithm */

const Quadtree = require("quadtree-lib")

function dist(x1, y1, x2, y2) {
  return Math.sqrt(Math.pow(x1 - x2, 2) + Math.pow(y1 - y2, 2))
}

function circleCollision(element1, element2) {
  return (
    dist(element1.x, element1.y, element2.x, element2.y) <
    element1.width + element2.width
  )
}

const quadtree = new Quadtree({
  width: 100,
  height: 100
})

const elements = [
  {x: 0, y: 0, width: 7, height: 7},
  {x: 5, y: 5, width: 1, height: 1}
]

quadtree.pushAll(elements)

console.log(quadtree.colliding(elements[0], circleCollision))
// [ { x: 5, y: 5, width: 1, height: 1 } ]
```

**Comment by elbywan** [comment] 2020-08-08 22:38
Ah and unless I'm mistaken, I think that in your collision algorithm you are using the width (diameter) instead of the radius. (see https://developer.mozilla.org/en-US/docs/Games/Techniques/2D_collision_detection)

**Comment by realTronsi** [comment] 2020-08-08 22:54
```javascript
let colliding = qt.colliding({
    x: x,
    y: y,
    width: radius,
    height: radius
},
function (element1, element2) {
    //circle collision
}
```

When I run this, elements from other sectors of the quadtree aren't getting pushed into the colliding array.
This is especially illustrated when I set the maxElements to 1, then sometimes the collision doesnt work if more than one element is colliding with it.

**Comment by elbywan** [comment] 2020-08-08 23:11
> elements from other sectors of the quadtree

I'm sorry but I don't understand this part, it seems to me that colliding elements should always be located in the same sector (except overlapping/oversized elements that are always compared) since this is the fundamental principle of a quadtree.

Could you share a complete example (with a list of elements & coordinates) that I could run to reproduce the issue?

**Comment by realTronsi** [comment] 2020-08-09 01:48
```javascript
const Quadtree = require("quadtree-lib")

function dist(x1, y1, x2, y2) {
  return Math.sqrt(Math.pow(x1 - x2, 2) + Math.pow(y1 - y2, 2))
}

function circleCollision(element1, element2) {
  return (
    dist(element1.x, element1.y, element2.x, element2.y) <
    element1.width + element2.width
  )
}

const quadtree = new Quadtree({
  width: 100,
  height: 100
})

const elements = [
  {x: 0, y: 0, width: 7, height: 7},
  {x: 5, y: 5, width: 1, height: 1}
]

quadtree.pushAll(elements)

console.log(quadtree.colliding({
  x: 20,
  y: 20,
  width: 20,
  height: 20
}, circleCollision))
```
I changed the numbers a bit and the logging is giving me an empty array.

**Comment by elbywan** [comment] 2020-08-09 08:26
> I changed the numbers a bit and the logging is giving me an empty array.

Looks normal to me,`x` and `y` are the top-left most coordinates and there is no element colliding with a circle spanning from (20, 20) to (40, 40). And you might also want to double check your collision algorithm.

**Comment by realTronsi** [comment] 2020-08-09 12:07
> a circle spanning from (20, 20) to (40, 40)

Ah, I assumed that the (20, 20) would the circle's center. All of my code is based around the coordinates being the center, and I'm not sure if its feasible to change thousands of lines of code, so is there a quick fix to this?

**Comment by elbywan** [comment] 2020-08-09 16:18
> I'm not sure if its feasible to change thousands of lines of code, so is there a quick fix to this?

Well, it depends on your code but you could use an adapter function whenever you interact with the library, for instance something like:

```js

function adapter(element) {
    return {
        ...element,
        x: element.x - element.width/2,
        y: element.y - element.height/2
    }
}

// Then use adapter when interacting with the library, for instance when inserting elements:
quadtree.pushAll(elements.map(adapter))
```

In any case, this is not a bug on the `quadtree-lib` side so I'm closing the issue.

**Closed as completed by elbywan** 2020-08-09 16:18 UTC

**Comment by realTronsi** [comment] 2020-08-11 18:33
I've found the root of the problem:

```javascript
const Quadtree = require("quadtree-lib")

function dist(x1, y1, x2, y2) {
  return Math.sqrt(Math.pow(x1 - x2, 2) + Math.pow(y1 - y2, 2))
}

function circleCollision(element1, element2) {
  return (
    dist(element1.x, element1.y, element2.x, element2.y) <
    element1.width + element2.width
  )
}

const quadtree = new Quadtree({
  width: 100,
  height: 100,
  maxElements: 1
})

const elements = [
  {x: 5, y: 5, width: 7, height: 7},
  {x: 5, y: 5, width: 1, height: 1}
]

quadtree.pushAll(elements)

console.log(quadtree.colliding({
  x: 20,
  y: 20,
  width: 20,
  height: 20
}, circleCollision))
```

This outputs an empty array. I assume this is caused by the maxElements property, but if I increase it, would the effectiveness of the quadtree go down as well?

**Comment by elbywan** [comment] 2020-08-11 22:30
> This outputs an empty array.

As I said before, I think that your algorithm is not correct. The radius of the circle is **half** the `width`and `height` of the quadtree element.

In your example, it looks like the circles don't collide.

```js
// From https://developer.mozilla.org/en-US/docs/Games/Techniques/2D_collision_detection
var circle1 = {radius: 7/2, x: 5, y: 5}
var circle2 = {radius: 20/2, x: 20, y: 20}

var dx = circle1.x - circle2.x
var dy = circle1.y - circle2.y
var distance = Math.sqrt(dx * dx + dy * dy)

console.log(distance < circle1.radius + circle2.radius)
// false
```

**Comment by realTronsi** [comment] 2020-08-11 22:37
Ah sorry, I posted the wrong code, here is the actual code:

```javascript
const Quadtree = require("quadtree-lib")

function dist(x1, y1, x2, y2) {
  return Math.sqrt(Math.pow(x1 - x2, 2) + Math.pow(y1 - y2, 2))
}

function circleCollision(element1, element2) {
  return (
    dist(element1.x+element1.width/2, element1.y+element1.width/2, element2.x+element2.width/2, element2.y+element2.width/2) <
    element1.width/2 + element2.width/2
  )
}

const quadtree = new Quadtree({
  width: 100,
  height: 100,
  maxElements: 1
})

const elements = [
  {x: 5, y: 5, width: 7, height: 7},
  {x: 5, y: 5, width: 1, height: 1}
]

quadtree.pushAll(elements)

console.log(quadtree.colliding({
  x: 20,
  y: 20,
  width: 20,
  height: 20
}, circleCollision))
```

It is outputting an empty array even though their coordinates are the exact same.

**Comment by elbywan** [comment] 2020-08-11 22:42
Yes as I said before those circles do not collide.

Distance between circle (20, 20) and (5, 5) is `21.213203435596427`. Sum of the radii is `13.5`.

> It is outputting an empty array even though their coordinates are the exact same.

Are you talking about the two circles at (5, 5)? Because calling `.colliding` will only check collisions with the provided element argument which is the (20, 20) circle.

**Comment by realTronsi** [comment] 2020-08-11 22:52
Ah oops, I got confused again, but here:

```javascript
const Quadtree = require("quadtree-lib")

function dist(x1, y1, x2, y2) {
  return Math.sqrt(Math.pow(x1 - x2, 2) + Math.pow(y1 - y2, 2))
}

function circleCollision(element1, element2) {
  return (
    dist(element1.x+element1.width/2, element1.y+element1.width/2, element2.x+element2.width/2, element2.y+element2.width/2) <
    element1.width/2 + element2.width/2
  )
}

const quadtree = new Quadtree({
  width: 100,
  height: 100,
  maxElements: 1
})

const elements = [
  {x: 5, y: 5, width: 7, height: 7},
  {x: 5, y: 5, width: 1, height: 1}
]

quadtree.pushAll(elements)

console.log(quadtree.colliding({
  x: 3,
  y: 3,
  width: 20,
  height: 20
}, circleCollision)) //[ { x: 5, y: 5, width: 7, height: 7 } ]
```

It returns only 1 of the two elements.

**Comment by elbywan** [comment] 2020-08-11 23:04
```js
console.log(circleCollision(elements[1], {
  x: 3,
  y: 3,
  width: 20,
  height: 20
}))
// false
```

**Comment by realTronsi** [comment] 2020-08-11 23:08
That makes no sense though, as both should be colliding.

```javascript
const Quadtree = require("quadtree-lib")

function dist(x1, y1, x2, y2) {
  return Math.sqrt(Math.pow(x1 - x2, 2) + Math.pow(y1 - y2, 2))
}

function circleCollision(element1, element2) {
  return (
    dist(element1.x+element1.width/2, element1.y+element1.width/2, element2.x+element2.width/2, element2.y+element2.width/2) <
    element1.width/2 + element2.width/2
  )
}

const quadtree = new Quadtree({
  width: 100,
  height: 100,
  maxElements: 1
})

const elements = [
  {x: 5, y: 5, width: 7, height: 7},
  {x: 5, y: 5, width: 3, height: 3}
]

quadtree.pushAll(elements)

console.log(quadtree.colliding({
  x: 5,
  y: 5,
  width: 20,
  height: 20
}, circleCollision)) //[ { x: 5, y: 5, width: 7, height: 7 } ]
```
It still only detects one collision despite all three having the same coordinates. The circle with diameter of 20 should span across both circles

**Comment by elbywan** [comment] 2020-08-11 23:15
> That makes no sense though, as both should be colliding.

Sure, but I doubt that it has anything to do with the library.

```js
function dist(x1, y1, x2, y2) {
  return Math.sqrt(Math.pow(x1 - x2, 2) + Math.pow(y1 - y2, 2))
}

function circleCollision(element1, element2) {
  return (
    dist(element1.x+element1.width/2, element1.y+element1.width/2, element2.x+element2.width/2, element2.y+element2.width/2) <
    element1.width/2 + element2.width/2
  )
}

const elements = [
  {x: 5, y: 5, width: 7, height: 7},
  {x: 5, y: 5, width: 3, height: 3}
]

const argumentElement = {
  x: 5,
  y: 5,
  width: 20,
  height: 20
}

console.log(circleCollision(elements[0], argumentElement))
// true

console.log(circleCollision(elements[1], argumentElement))
// false
```

**Comment by elbywan** [comment] 2020-08-11 23:16
I'm sorry but this is taking too much of my time.

**Comment by realTronsi** [comment] 2020-08-11 23:17
Oh ok, I guess I'll figure it out
